services:
  - type: web
    name: coffee-bot
    env: dotnet
    plan: free
    branch: main
    buildCommand: dotnet publish -c Release
    startCommand: dotnet ./bin/Release/net8.0/CoffeeBot.dll
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
